"""index transaction account and category fks

Revision ID: f76376f1e3bf
Revises: fe48967d36b6
Create Date: 2026-09-08 02:41:48.911736

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f76376f1e3bf"
down_revision: str | Sequence[str] | None = "fe48967d36b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_transactions_user_id_account_id",
        "transactions",
        ["user_id", "account_id"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_user_id_category_id",
        "transactions",
        ["user_id", "category_id"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_user_id_to_account_id",
        "transactions",
        ["user_id", "to_account_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_user_id_to_account_id", table_name="transactions")
    op.drop_index("ix_transactions_user_id_category_id", table_name="transactions")
    op.drop_index("ix_transactions_user_id_account_id", table_name="transactions")
    # ### end Alembic commands ###
