import { Component, computed, input } from '@angular/core';

const ICON_FILES = {
  home: 'home.svg',
  wallet: 'wallet.svg',
  swap: 'swap.svg',
  tag: 'tag.svg',
  target: 'target.svg',
  chart: 'chart.svg',
  settings: 'settings.svg',
  sun: 'sun.svg',
  moon: 'moon.svg',
  globe: 'globe.svg',
  menu: 'menu.svg',
  close: 'close.svg',
  plus: 'plus.svg',
  trash: 'trash.svg',
  pencil: 'pencil.svg',
  chevronDown: 'chevron-down.svg',
  chevronRight: 'chevron-right.svg',
  check: 'check.svg',
  alertTriangle: 'alert-triangle.svg',
  repeat: 'repeat.svg',
  archive: 'archive.svg',
  arrowUpRight: 'arrow-up-right.svg',
  arrowDownLeft: 'arrow-down-left.svg',
  refresh: 'refresh.svg',
  search: 'search.svg',
  funnel: 'funnel.svg',
  eye: 'eye.svg',
  eyeOff: 'eye-off.svg',
  command: 'command.svg',
  cornerDownLeft: 'corner-down-left.svg',
  zap: 'zap.svg',
  grip: 'grip.svg',
  bank: 'bank.svg',
  piggy: 'piggy.svg',
  apple: 'apple.svg',
  baby: 'baby.svg',
  banknote: 'banknote.svg',
  basket: 'basket.svg',
  bed: 'bed.svg',
  beer: 'beer.svg',
  bell: 'bell.svg',
  bike: 'bike.svg',
  bitcoin: 'bitcoin.svg',
  book: 'book.svg',
  bookmark: 'bookmark.svg',
  briefcase: 'briefcase.svg',
  building: 'building.svg',
  bus: 'bus.svg',
  cake: 'cake.svg',
  calculator: 'calculator.svg',
  calendar: 'calendar.svg',
  camera: 'camera.svg',
  car: 'car.svg',
  cart: 'cart.svg',
  clock: 'clock.svg',
  cloud: 'cloud.svg',
  coffee: 'coffee.svg',
  coins: 'coins.svg',
  creditCard: 'credit-card.svg',
  droplet: 'droplet.svg',
  dumbbell: 'dumbbell.svg',
  film: 'film.svg',
  firstAid: 'first-aid.svg',
  flag: 'flag.svg',
  flame: 'flame.svg',
  folder: 'folder.svg',
  fuel: 'fuel.svg',
  gamepad: 'gamepad.svg',
  gem: 'gem.svg',
  gift: 'gift.svg',
  glasses: 'glasses.svg',
  graduationCap: 'graduation-cap.svg',
  hammer: 'hammer.svg',
  handCoins: 'hand-coins.svg',
  headphones: 'headphones.svg',
  heart: 'heart.svg',
  invoice: 'invoice.svg',
  key: 'key.svg',
  laptop: 'laptop.svg',
  leaf: 'leaf.svg',
  lightbulb: 'lightbulb.svg',
  lock: 'lock.svg',
  luggage: 'luggage.svg',
  mail: 'mail.svg',
  mapPin: 'map-pin.svg',
  music: 'music.svg',
  package: 'package.svg',
  palette: 'palette.svg',
  parking: 'parking.svg',
  paw: 'paw.svg',
  percent: 'percent.svg',
  phone: 'phone.svg',
  pieChart: 'pie-chart.svg',
  pill: 'pill.svg',
  pizza: 'pizza.svg',
  plane: 'plane.svg',
  plug: 'plug.svg',
  receipt: 'receipt.svg',
  safe: 'safe.svg',
  scale: 'scale.svg',
  scissors: 'scissors.svg',
  shield: 'shield.svg',
  shirt: 'shirt.svg',
  shoppingBag: 'shopping-bag.svg',
  smartphone: 'smartphone.svg',
  sneaker: 'sneaker.svg',
  sofa: 'sofa.svg',
  sparkles: 'sparkles.svg',
  star: 'star.svg',
  stethoscope: 'stethoscope.svg',
  ticket: 'ticket.svg',
  tools: 'tools.svg',
  tooth: 'tooth.svg',
  train: 'train.svg',
  trendingDown: 'trending-down.svg',
  trendingUp: 'trending-up.svg',
  truck: 'truck.svg',
  tv: 'tv.svg',
  umbrella: 'umbrella.svg',
  user: 'user.svg',
  users: 'users.svg',
  utensils: 'utensils.svg',
  wifi: 'wifi.svg',
  wine: 'wine.svg'
} as const;

export type IconName = keyof typeof ICON_FILES;

/** Every icon the app ships, for pickers that let the user browse the full set. */
export const ICON_NAMES = Object.keys(ICON_FILES) as IconName[];

/**
 * Category/institution-relevant icons, grouped into sections for the icon
 * picker. Icons absent from every group (chevrons, menu, close, ...) are app
 * chrome and are not offered as user-choosable icons.
 */
export const ICON_GROUPS = {
  money: [
    'wallet',
    'bank',
    'piggy',
    'chart',
    'target',
    'swap',
    'repeat',
    'creditCard',
    'coins',
    'banknote',
    'receipt',
    'invoice',
    'calculator',
    'trendingUp',
    'trendingDown',
    'pieChart',
    'bitcoin',
    'gem',
    'safe',
    'handCoins',
    'scale',
    'percent'
  ],
  food: ['utensils', 'cart', 'basket', 'coffee', 'beer', 'wine', 'pizza', 'cake', 'apple'],
  transport: ['car', 'fuel', 'bus', 'train', 'plane', 'bike', 'parking', 'truck'],
  home: [
    'home',
    'zap',
    'trash',
    'building',
    'key',
    'sofa',
    'bed',
    'lightbulb',
    'droplet',
    'flame',
    'wifi',
    'tools',
    'plug'
  ],
  shopping: ['tag', 'shoppingBag', 'shirt', 'sneaker', 'scissors', 'sparkles', 'gift'],
  health: ['heart', 'stethoscope', 'pill', 'firstAid', 'dumbbell', 'tooth', 'glasses'],
  entertainment: [
    'gamepad',
    'music',
    'film',
    'tv',
    'headphones',
    'camera',
    'smartphone',
    'laptop',
    'cloud',
    'book',
    'ticket'
  ],
  work: ['archive', 'graduationCap', 'briefcase', 'hammer', 'palette'],
  people: ['globe', 'baby', 'paw', 'users', 'user', 'luggage', 'mapPin', 'leaf'],
  general: [
    'star',
    'bell',
    'calendar',
    'bookmark',
    'flag',
    'clock',
    'mail',
    'phone',
    'lock',
    'folder',
    'umbrella',
    'shield',
    'package'
  ]
} as const satisfies Record<string, readonly IconName[]>;

export type IconGroup = keyof typeof ICON_GROUPS;

/**
 * Renders the app's standalone SVG assets as CSS masks. The mask inherits
 * `currentColor`, so existing text-color utilities and dynamic institution
 * colors continue to theme icons without duplicating SVG markup in Angular.
 */
@Component({
  selector: 'app-icon',
  templateUrl: './icon.html',
  styleUrl: './icon.scss'
})
export class Icon {
  readonly name = input.required<IconName>();
  readonly size = input(20);

  protected readonly iconUrl = computed(() => `url('/icons/${ICON_FILES[this.name()]}')`);
}
